"use client";

import { useState } from "react";
import EnableTwoFactorModal from "./EnableTwoFactorModal";

interface TwoFactorCardProps {
    enabled: boolean;
    onEnabled: () => void;
}

export default function TwoFactorCard({
    enabled,
    onEnabled,
}: TwoFactorCardProps) {
    const [open, setOpen] = useState(false);

    return (
        <>
            <div className="rounded-xl border bg-white p-6 shadow-sm">

                <div className="flex items-start justify-between">

                    <div>

                        <h3 className="text-lg font-semibold">
                            Two-Factor Authentication
                        </h3>

                        <p className="mt-2 text-sm text-gray-500">
                            Protect your account with an additional
                            verification code generated by an
                            authenticator application.
                        </p>

                    </div>

                    <div>

                        {enabled ? (
                            <span className="rounded-full bg-green-100 px-3 py-1 text-sm font-medium text-green-700">
                                Enabled
                            </span>
                        ) : (
                            <span className="rounded-full bg-gray-100 px-3 py-1 text-sm font-medium text-gray-700">
                                Disabled
                            </span>
                        )}

                    </div>

                </div>

                <div className="mt-6 flex gap-3">

                    {!enabled && (
                        <button
                            onClick={() => setOpen(true)}
                            className="rounded-lg bg-black px-5 py-2 font-medium text-white transition hover:bg-gray-800"
                        >
                            Enable 2FA
                        </button>
                    )}

                    {enabled && (
                        <>
                            <button
                                className="rounded-lg border px-5 py-2 font-medium transition hover:bg-gray-100"
                            >
                                Recovery Codes
                            </button>

                            <button
                                className="rounded-lg bg-red-600 px-5 py-2 font-medium text-white transition hover:bg-red-700"
                            >
                                Disable 2FA
                            </button>
                        </>
                    )}

                </div>

            </div>

            <EnableTwoFactorModal
                open={open}
                onClose={() => setOpen(false)}
                onEnabled={() => {
                    setOpen(false);
                    onEnabled();
                }}
            />
        </>
    );
}